# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.8
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: flake8
        args: [--config, /home/Canonical-flask-app/.flake8]
        name: flake8
        language: system
        entry: flake8
        types: [python]
        stages: [commit]
    -   id: pylint
        args:
          [
            "--rcfile=/home/Canonical-flask-app/.pylintrc",
            "--output-format=github",
          ]
        name: pylint
        language: system
        entry: pylint
        types: [python]
        stages: [commit]
