version: "2.20"
services: 
  flask_api:
    build:
      context: ./
      dockerfile: ./FlaskApp.Dockerfile
    container_name: flask_container
    ports:
      - '5000:5000'
    volumes:
      - /var/www/Canonical-flask-app/ /var/www/Canonical-flask-app/
      #- /var/www/Canonical-flask-app/
