services: 
  flask_api:
    build:
      context: ./
      dockerfile: ./FlaskApp.Dockerfile
    container_name: flask_container
    ports:
      - '127.0.0.1:443:443'
    volumes:
      - ${PWD}/api:/var/www/Canonical-flask-app/api
      - ${PWD}/tests:/var/www/Canonical-flask-app/tests
    restart: always
