services: 
  flask_api:
    build:
      context: ./
      dockerfile: ./FlaskApp.Dockerfile
    container_name: flask_container
    ports:
      - '8080:5000'
    volumes:
      - ${PWD}/api:/var/www/Canonical-flask-app/api
    restart: always
