name: Staging - Build, deploy, unit and integration test

on:
  pull_request:
  push:
    branches:
      - master




jobs:
  build-and-local-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade --no-cache-dir pip
          python -m pip install --no-cache-dir pipenv
          pip install -r requirements.txt
      - name: Local unit and integrations test
        run: |
          python3 -m pytest
  deploy-docker-container-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the container
        run: docker-compose -f docker-compose.prod-qa.yml up -d
      - name: Docker container unit and integrations test
        run: |
          docker exec --workdir /var/www/Canonical-flask-app flask_container python3 -m pytest
