name: Staging - Build, deploy, unit and integration test

on:
  pull_request:
    branches:
      - staging
  #push:
    #branches:
      #- staging




jobs:
  build-and-local-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade --no-cache-dir pip
          python -m pip install --no-cache-dir pipenv
          pip install -r requirements.txt
      - name: Local unit and integrations test
        run: |
          python3 -m pytest
  deploy-docker-container-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the container
        run: docker-compose -f docker-compose.prod-qa.yml up -d
      - name: Docker container unit and integrations test
        run: |
          docker exec --workdir /var/www/Canonical-flask-app flask_container python3 -m pytest
  merge-request-to-prod:
    runs-on: ubuntu-latest
    needs: [build-and-local-test,deploy-docker-container-and-test]
    steps:
      - uses: actions/checkout@v4
        name: Check out code
      - name: Create merge/pull request
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          BRANCH: staging
        run: |
          git checkout staging
          gh pr create --head staging --title "Merge to Prod" --body "This is an automated PR to update prod"
          gh pr merge --auto --merge
